version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    certbot-setup:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'certbot --nginx -d ruanfergui.com.br -d www.ruanfergui.com.br --non-interactive --agree-tos --email ruan_guimaraes2004@hotmail.com'"
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
