version: '3.7'

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: always

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!} ; certbot renew; done'"

    certbot-setup:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'certbot certonly --webroot -w /var/www/certbot -d ruanfergui.com.br --email ruan_guimaraes2004@hotmail.com --agree-tos --no-eff-email && nginx -s reload'"
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - app
